[package]
name = "lattice-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
lattice-core = { workspace = true }
lattice-scene = { workspace = true }
lattice-render = { workspace = true }
egui = { workspace = true }
egui_dock = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
