[package]
name = "lattice-standalone"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
lattice-core = { workspace = true }
lattice-ui = { workspace = true }
lattice-render = { workspace = true, features = ["hot-reload"] }
eframe = { workspace = true }
egui = { workspace = true }
midir = { workspace = true }
