[package]
name = "harmonigraph-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
harmonigraph-core = { workspace = true }
harmonigraph-scene = { workspace = true }
harmonigraph-render = { workspace = true }
harmonigraph-perf = { workspace = true }
harmonigraph-take = { workspace = true }
egui = { workspace = true }
egui_dock = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
